language: bash
services: docker

env:
  - VERSION=6

before_script:
  - env | sort
  - cd "$VERSION"
  - image="jimexist/node-yarn:$VERSION"

script:
  - docker build -t "$image" .

after_script:
  - docker images

# vim:set et ts=2 sw=2:
